project_id = "ifpjqewobfwzxreszjgm"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
